### ISSUE TITLE
package 'corpor' missing

### ISSUE THREAD

**Issue by AndrewLJackson** [TGuillerme/mulTree#35]
hi Thomas

I'm teaching a course using mulTree next week. Lots of people reporting that it is not installing first time, with the package `corpor` being missing.

I had a quick look, but can't see where exactly in mulTree this call is, and it might be within MCMCglmm, but install.packages('corpor') prior to installing mulTree fixes it.
cheers
andrew

**Comment by TGuillerme** [comment]
Hi Andrew,

That's really odd. The installation ran smoothly with `R CMD Check` on my machine and on `travis`. On the other hand, on a different machine, I needed to install `curl` and `caper` (but not `corpcor`). I will add a line in the `README` for the installation to install these packages prior to `mulTree` as a quick fix and will have a proper debugging session later on next week.

Thanks for noticing the issue!

Cheers,
Thomas
