### ISSUE TITLE
add argument to suppress overwrite files warning

### ISSUE THREAD

**Issue by AndrewLJackson** [TGuillerme/mulTree#49]
line 189 of multree.R checks to see if the output files already exist and prompts for user intervention. It would be good if there was as an input argument to suppress this and overwrite without the prompt, but perhaps tell the user this was done. This would facilitate easier creation of Rmarkdown files or programmatic implementations of mulTree where it needs automating in a loop.

**Comment by TGuillerme** [comment]
Great idea! Fixed in 1.3.1, just add `ask = FALSE` to the `mulTree()` function.

**Comment by AndrewLJackson** [comment]
magic! nice one Thomas
--
––––––––––––
Dr Andrew Jackson, PhD, FTCD
Associate Professor
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.

On 18 Jul 2017, at 13:27, Thomas Guillerme <notifications@github.com<mailto:notifications@github.com>> wrote:


Great idea! Fixed in 1.3.1, just add ask = FALSE to the mulTree() function.
